config/routes.rb
Btww1::Application.routes.draw do

  get '/contest_ended' => 'greetings#contest_ended', :as => :contestended

  get '/index' => 'greetings#index'
  get '/forgot-password' => 'greetings#forgot-password'
  post '/forgot-password' => 'users#reset_password'

  get '/activate' => 'greetings#activate', :as => :activate

  root :to => 'teams#index'
  
  get '/users/:id/chooseteam' => 'users#edit', :as => :chooseteam
  get '/users/:id/completeprofile' => 'users#completeprofile', :as => :completeprofile
  get '/users/:id/surveyinfo' => 'users#surveyinfo', :as => :surveyinfo
  get '/users/activate' => 'users#activate', :as => :activate_account

  match '/auth/:facebook/callback', to: 'sessions#fb_auth'

  resources :sessions
  
  get '/logout' => 'sessions#destroy', :as => :logout
  
  get '/reports' => 'reports#index', :as => :reports
  get '/reports/commute-comments' => 'reports#commute_comments'
  get '/reports/commute-comments/wordcloud' => 'reports#wordcloud'
  
  get '/reports/teams' => 'reports#teams', :as => :teamsreport
  get '/reports/users' => 'reports#users', :as => :usersreport
  
  get '/reports/team_report' => 'reports#team_report', :as => :teamcsvfile
  get '/reports/user_report' => 'reports#user_report', :as => :usercsvfile

  resources :awards

  resources :commutes

  get '/teams/count' => 'teams#team_count', :as => :teamcount

  resources :teams

  resources :users do
    resources :commutes
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  
  has_secure_password
  
  has_many :commutes
  belongs_to :team
  has_many :won_awards
  
  validates_presence_of :fname
  validates_presence_of :lname
  validates_presence_of :email
  validates_uniqueness_of :email
  validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i
  


  def full_name
    return fname + ' ' + lname
  end

  def commutes_that_count
    commutes.where(:commute_date => '2012-06-09'.. '2012-06-15')
  end

  def mileage
  mileage = 0
	  commutes_that_count.each do |commute|
					mileage = mileage + commute.mileage
		end
	return (mileage * 100).round.to_f / 100
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json

  before_filter :find_user, :except =>  [:index, :new, :create, :reset_password, :send_confirm, :activate]
  before_filter :require_istheuser, :except =>  [:index, :show, :new, :create, :reset_password, :send_confirm, :activate]

  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @title = "#{@user.full_name} | Bike Commuter Challenge"
    if @user.team_id != nil
      @award = Award.where(:company_type => @user.team.company_type,
                           :company_size_range => @user.team.company_size_range,
                           :goal => 'Participation Rate')
      logger.debug "Award is #{@award}"
      logger.debug "Award ID is #{@award[0].id}"
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new
    @title = "Register a New User | Bike Commuter Challenge"
      if params[:team_id] != nil
        @user.team_id = params[:team_id]
        @team = Team.find(params[:team_id])
      end
    @user.btww_email_list = true
    @user.general_email_list = true
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @title = "Edit User | Bike Commuter Challenge"
    
    if !isadmin? && @user.team == nil
      render 'chooseteam'
    end
    if params[:team_id] != nil
      @user.team_id = params[:team_id]
    end
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        
        if @user.team != nil
          update_team_stats(@user.team)          
        end

        if @user.uid == nil
          
            @user.update_attributes(:activation_code => rand(36**18).to_s(36))
            UserMailer.email_confirmation(@user).deliver
            format.html {redirect_to new_session_url, notice: "A confirmation email was sent to #{@user.email}.
                                                                         You must click on the confirmation link to confirm your account.
                                                                         Don't forget to check your spam folder just in case."}
        else
          if logged_in? == false
            session[:user_id] = @user.id
          end
          if @user.team != nil
          format.html { redirect_to team_url(@user.team.id), notice: "You're in!  Now invite more co-workers!" }
          format.json { render json: @user, status: :created, location: @user }
          else
          format.html { redirect_to chooseteam_url(@user.id) }
          end
          
        end
      
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end

  end




  # PUT /users/1
  # PUT /users/1.json
  def update
    old_team = @user.team
    
    respond_to do |format|
      
      if @user.update_attributes(params[:user])

          if old_team != nil
            update_team_stats(old_team)
          end

          if @user.team != nil
            update_team_stats(@user.team)
          end
 
 
          if @user.team == nil
              format.html { redirect_to chooseteam_url(@user.team) } 
          elsif old_team != @user.team            
            format.html { redirect_to team_url(@user.team), notice: "You're in!  Now invite more co-workers!" }
          else
            format.html { redirect_to @user, notice: 'User was successfully updated.' }
            format.json { head :ok }
          end

      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end

    end
  end
  

  def reset_password
    # @user = User.find_by_email(params[:email])
    @user = User.where("email = ?", params[:email]).first
    if @user
      @pwd = rand(100000)
      @user.update_attributes(:password => @pwd, :password_confirmation => @pwd)
      UserMailer.password_email(@user, @pwd).deliver
      redirect_to new_session_url, notice: "An email was sent to #{@user.email}. Don't forget to check your spam folder just in case."
    else
      redirect_to '/forgot-password', notice: "Sorry, there is no Bike Commuter Challenge account setup for #{params[:email]}. Try a different email address."
    end
  end

  def activate
    @user = User.find_by_id(params[:id])
    logger.debug "user is #{@user}"
    if params[:activation_code] == @user.activation_code
      @user.update_attributes(:activation_code => 'activated-2013')
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Your account is activated! Let the games begin!"
    else
      redirect_to root_url, notice: "Bad link, try again with the link from your re-activation email."
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
      if @user.commutes.count > 0
        @user.commutes.each do |commute|
          commute.destroy
        end
      end
    team = @user.team    
    
    if @user.destroy
      if team != nil
        update_team_stats(team)
      end
      
      respond_to do |format|
        format.html { redirect_to teams_url, notice: 'User was successfully deleted.' }
        format.json { head :ok }
      end

    else
      format.html { render action: "show" }
      format.json { render json: @user.errors, status: :unprocessable_entity }      
    end

  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<div id=new-user-required-left>
<h3>Required Information</h3>
  <div class="field">
    <%= f.label :fname, "First Name" %>
    <%= f.text_field :fname %>
  </div><br />
  <div class="field">
    <%= f.label :lname, "Last Name" %>
    <%= f.text_field :lname %>
  </div><br />	
  <div class="field">
    <%= f.label :email, "Email Address" %>
    <%= f.text_field :email %>
  </div><br />
  <div class="field">
    <%= f.label :password, "Password" %>
    <%= f.password_field :password %>
  </div><br />
  <div class="field">
    <%= f.label :password_confirmation, "Password Confirmation" %>
    <%= f.password_field :password_confirmation %>
  </div><br />
	
	<% if isadmin? %>
	  <div class="field">
	    <%= f.label :isadmin, "Check box if this User should have Admin rights" %>
	    <%= f.check_box :isadmin %>
	  </div><br />
	<% end %>

  <div class="field">
	<% if @user.id == nil %>
   		<%= f.label :team_id, "Team: If your company isn't listed, you can create it in the next step." %>
	<% else %>
   		<%= f.label :team_id, "Team:" %>
   		Don't see your team? <%= link_to "Create a New Team", new_team_url %>
	<% end %>
    <p><%= f.collection_select(:team_id, Team.order('company asc'), :id, :company, :prompt => "Select your Team") %></p>
  </div>
</div>

<div id=fun-stuff>
<h3>Fun Stuff</h3>
<br />
  <div class="field">
    <%= f.label :isnewbie, "First Time Biking to Work?" %>
    <%= f.check_box :isnewbie %>
  </div>
<br />
  <div class="field">
    <%= f.label :bikerclass, "Primary Biker Type" %>
    <%= f.select(:bikerclass, ['Recreational', 'Commuter/Transportation', 'Roadie', 'MTB/Cross', 'BMX'], :prompt => "Select One") %>
<br />
  </div>
	<br>
	<div class="field">
	  <%= f.label :btww_email_list, "Send me tips on How to Bike To Work, Pit Stops, Parties, and Winners of Commuter Challenge!" %>
	  <%= f.check_box :btww_email_list %>
	</div>
	<br>
	<div class="field">
	  <%= f.label :general_email_list, "Send me updates on events and legislation pertaining to cycling in Chicago and Illinois!" %>
	  <%= f.check_box :general_email_list %>
	</div>

</div>

<div id=demo-stuff>
<h3>Important Stuff</h3>
<p>These survey questions are optional, for planning purposes only, and will only be shared at an aggregate level -- not displayed on your profile page.</p>
  <div class="field">
    <!-- <%= f.label :gender, "Gender" %> -->
    <%= f.select(:gender, ['Female', 'Male', 'Other'], :prompt => "Gender") %>
  </div>
  <div class="field">
    <!-- <%= f.label :ethnicity, "Would you describe yourself as:" %> -->
    <%= f.select(:ethnicity, ['American Indian/Native American', 'Asian', 'Black/African American', 'Hispanic/Latino', 'White/Caucasian', 'Pacific Islander', 'Other'], :prompt => "Ethnicity") %>
  </div>
	<div class="field">
	  <!-- <%= f.label :age_range, "What is your age range?" %> -->
      <%= f.select(:age_range, ['18-34', '35-44', '45-54', '55-65', '  65+'], :prompt => "Age Range") %>
	</div>
	

	<div class="field">
	<div id="home-zip">
	  <%= f.label :home_zip_code, "HOME zip code" %>
      <%= f.text_field :home_zip_code , :style=>'width:100px'%>
	</div>
	</div>
	<div class="field">
	<div id="work-zip">
	  <%= f.label :work_zip_code, "WORK zip code" %>
      <%= f.text_field :work_zip_code , :style=>'width:100px'%>
		</div>
	</div>
	</div>
</div>

<br>
<div id=submit-form>
	<button type="submit" class="btn btn-large btn-success"> Create My Account!
	</button>

<!--   <div class="btn btn-large btn-success">
    <%= f.submit "Create my Account!"%>
  </div> -->
</div>
<% end %>

app/views/users/_omniauthform.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fname, "First Name" %>
    <%= f.text_field :fname %>
  </div><br>
  <div class="field">
    <%= f.label :lname, "Last Name" %>
    <%= f.text_field :lname %>
  </div><br />
	<% if isadmin? %>
	  <div class="field">
	    <%= f.label :isadmin, "Check box if this User should have Admin rights" %>
	    <%= f.check_box :isadmin %>
	  </div><br />
	<% end %>
  <div class="field">
   	<%= f.label :team_id, "Team: If your company isn't listed, you can create it in the next step." %>
    <p><%= f.collection_select(:team_id, Team.order('company asc'), :id, :company, :prompt => "Select your Team") %></p>
  </div><br>
  <div class="field">
    <%= f.label :isnewbie, "First Time Biking to Work?" %>
    <%= f.check_box :isnewbie %>
  </div><br>
	<% if isadmin? %>
  <div class="field">
    <%= f.label :email, "Email Address" %>
    <%= f.text_field :email %>
  </div><br>
  <div class="field">
    <%= f.label :password, "Password" %>
    <%= f.password_field :password %>
  </div><br />
  <div class="field">
    <%= f.label :password_confirmation, "Password Confirmation" %>
    <%= f.password_field :password_confirmation %>
  </div><br />
	<% end %>
	  <div class="field">
	    <%= f.label :bikerclass, "Primary Biker Type" %>
	    <%= f.select(:bikerclass, ['Recreational', 'Commuter/Transportation', 'Roadie', 'MTB/Cross', 'BMX'], :prompt => "Select One") %>
	<br />
	  </div>
	<br>
	<div class="field">
	  <%= f.label :btww_email_list, "Would you like to receive tips on How to Bike To Work and info on Pit Stops, Parties, and Winners of Commuter Challenge?" %>
	  <%= f.check_box :btww_email_list %>
	</div>
	<br>
	<div class="field">
	  <%= f.label :general_email_list, "Would you like to receive updates on events and policy efforts of the Active Transportation Alliance as it pertains to the state of cycling in Chicago and Illinois?" %>
	  <%= f.check_box :general_email_list %>
	</div>
	<br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_surveyform.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fname, "First Name" %>
    <%= f.text_field :fname %>
  </div><br>
  <div class="field">
    <%= f.label :lname, "Last Name" %>
    <%= f.text_field :lname %>
  </div><br />
	<% if isadmin? %>
	  <div class="field">
	    <%= f.label :isadmin, "Check box if this User should have Admin rights" %>
	    <%= f.check_box :isadmin %>
	  </div><br />
	<% end %>
  <div class="field">
   	<%= f.label :team_id, "Team: If your company isn't listed, you can create it in the next step." %>
    <p><%= f.collection_select(:team_id, Team.order('company asc'), :id, :company, :prompt => "Select your Team") %></p>
  </div><br>
  <div class="field">
    <%= f.label :isnewbie, "First Time Biking to Work?" %>
    <%= f.check_box :isnewbie %>
  </div><br>
	<% if isadmin? %>
  <div class="field">
    <%= f.label :email, "Email Address" %>
    <%= f.text_field :email %>
  </div><br>
  <div class="field">
    <%= f.label :password, "Password" %>
    <%= f.password_field :password %>
  </div><br />
  <div class="field">
    <%= f.label :password_confirmation, "Password Confirmation" %>
    <%= f.password_field :password_confirmation %>
  </div><br />
	<% end %>
	  <div class="field">
	    <%= f.label :bikerclass, "Primary Biker Type" %>
	    <%= f.select(:bikerclass, ['Recreational', 'Commuter/Transportation', 'Roadie', 'MTB/Cross', 'BMX'], :prompt => "Select One") %>
	<br />
	  </div>
	<br>
	<div class="field">
	  <%= f.label :btww_email_list, "Would you like to receive tips on How to Bike To Work and info on Pit Stops, Parties, and Winners of Commuter Challenge?" %>
	  <%= f.check_box :btww_email_list %>
	</div>
	<br>
	<div class="field">
	  <%= f.label :general_email_list, "Would you like to receive updates on events and policy efforts of the Active Transportation Alliance as it pertains to the state of cycling in Chicago and Illinois?" %>
	  <%= f.check_box :general_email_list %>
	</div>
	<br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/chooseteam.html.erb
<h1>Select Team for <%= @user.full_name %></h1>

<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>

  <% end %>

<br>
<br>

<h3>Select an Existing Team</h3>

  <div class="field">
    <p><%= f.collection_select(:team_id, Team.order('company asc'), :id, :company, :prompt => "Select your Team") %></p>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<!-- <h2>OR</h2>
<br>
<%= button_to "Create a New Team", new_team_url, :method => 'get' %> -->

app/views/users/completeprofile.html.erb
<h1>Edit <%= @user.full_name %></h1>

<p id="notice"><%= notice %></p>

	<% if @user.provider !=nil  %>
		<%= render 'omniauthform' %>
	<% else  %>
	<%= render 'form' %>
	<% end  %>

<%= link_to 'Cancel', @user %>

app/views/users/edit.html.erb
<h1>Edit <%= @user.full_name %></h1>

<p id="notice"><%= notice %></p>

	<% if @user.provider !=nil  %>
		<%= render 'omniauthform' %>
	<% else  %>
	<%= render 'form' %>
	<% end  %>

<%= link_to 'Cancel', @user %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Not Allowed</h1>

app/views/users/new.html.erb
<!-- <h1>Sorry, User Registration is now closed</h1> -->
<% if params[:team_id] != nil %>
	<h1>Join Team <%= @team.company %>! </h1>
<% else %>
	<h1>Create a User Profile</h1>
<% end %>
<p>Prefer not to remember another password? Instead... <%= link_to image_tag("login_fb.jpeg", :border=>0), '/auth/facebook' %></p>
<br>
<%= render 'form' %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @user.full_name %>'s Bike Commuting Stats</h2>
<br>
<p>
  <b>Biker: </b>
  <%= @user.fname %>  <%= @user.lname %>
	<% if get_user == @user  %>
		<% if isadmin?  %>
			<%= link_to '(Edit Profile)', edit_user_path(@user) %>
		<% else %>
			<%= link_to '(Edit Profile)', edit_user_path(@user) %>
		<% end %>

	<% else  %>
		<% if isadmin?  %>
			<% if @user.team_id != nil && @user.team.leader != @user.id %>
				<%= link_to '(Edit Profile)', edit_user_path(@user) %> | <%= link_to '(Delete User)', user_url(@user), :method => 'delete', :confirm => "Hello, Admin User. Are you sure you want to delete User #{@user.full_name}? #{@user.commutes.count} commute(s) logged by this user will also be deleted." %>
			<% elsif @user.team_id == nil %>
				<%= link_to '(Edit Profile)', edit_user_path(@user) %> | <%= link_to '(Delete User)', user_url(@user), :method => 'delete', :confirm => "Hello, Admin User. Are you sure you want to delete User #{@user.full_name}? #{@user.commutes.count} commute(s) logged by this user will also be deleted." %>
			<% else %>
				<%= link_to '(Edit Profile)', edit_user_path(@user) %>
			<% end %>
		<% end %>
	<% end  %>
</p>

<% if @user.provider != nil  %>
<p> <%= image_tag("http://graph.facebook.com/#{@user.uid}/picture?type=square", :width => '60') %> </p>
<% end  %>

<p><% if @user.team_id != nil  %>
  <b>Team:</b> <%= link_to "#{@user.team.company}", team_url(@user.team.id) %>
<% else  %>
	<% if logged_in? && get_user.id ==  @user.id %>
		<%= link_to "Add Your Team", edit_user_url(@user.id) %>
	<% end  %>
<% end %>
</p>
<p>
  <b>Primary Biker Type:</b>
  <%= @user.bikerclass %>
</p>

	<% if @user.isnewbie == true %>
<p><strong><%= "#{@user.fname} is a Bike Commuter Newbie!" %></strong></p>
	<% else %>
	<% end %>
</p>
	 
	<table class="table table-striped table-bordered table-condensed">

		<tr>
		<th> Total Logged Commutes </th>
		<th> Total Logged Mileage </th>
	 	<th> Qualifying Commutes (during Commuter Challenge) </th>
	 	<th> Qualifying Mileage </th>
		</tr>

		<tr>
		<td> <%= @user.commutes.count %> </td>
				<% mileage = 0 %>
				<% @user.commutes.each do |commute| %>
				<% mileage = mileage + commute.distance %>
				<% end %>
		<td> <%= mileage %> </td>
		<td> <%= @user.commutes_that_count.count %> </td>
				<% mileage = 0 %>
				<% @user.commutes_that_count.each do |commute| %>
				<% mileage = mileage + commute.distance %>
				<% end %>
			<td> <%= mileage %> </td>
		</tr>

	</table>

	<table>
		<!-- <% if logged_in? && @user == get_user %>		
			<td><%= button_to "+ Add a Commute", new_commute_url, :user_id => get_user.id, :method => 'get' %></td>
		<% end %> -->
		<% if @user.team != nil && @user.team.company_size_range != nil && @user.team.company_size_range != "" %>
			<td><%= button_to "Check the Scoreboard for #{@user.team.company}", award_url(users_scoreboard(@user).id), :method => 'get' %></td>
		<% end %>
	</table>


<div id='fb-share-button'> </div>

<div id='fb-root'></div>
	<i>Share <%= @user.fname %>'s Progress! </i>
    <script src='http://connect.facebook.net/en_US/all.js'></script>
    <p><a onclick='postToFeed(); return false;'> <%= image_tag("facebook_share_button.jpg", :width => '60') %></a>


    <script> 
       FB.init({appId: 204090116364336, status: true, cookie: true});

      function postToFeed() {

        // calling the API ...
        var obj = {
          method: 'feed',
          link: '<%= url_for user_url %>',
          picture: 'http://activetrans.org/htmlemail/ata.png',
          name: 'Bike To Work Week stats for <%= @user.full_name %>!',
          caption: 'Active Transportation Alliance Commuter Challenge',
          description: 'Sign up your company to compete!',
		  message: 'Check out my progress on Bike Commuter Challenge!'
        };

        function callback(response) {
          document.getElementById('msg').innerHTML = "Post ID: " + response['post_id'];
        }

        FB.ui(obj, callback);
      }

    </script>

	<a href="https://twitter.com/share" class="twitter-share-button" data-text="Check out <%= @user.fname %>'s progress on Bike Commuter Challenge!" data-count="none">Tweet</a>
	<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script></p>
	    <p id='msg'></p>


<% if after_btww_start? %>
 	<% if @user.commutes_that_count.count > 0 %>
		<p>
		  <b><%= @user.fname %>'s Commutes During Commuter Challenge (Jun 9 - Jun 15):</b>
		</p>
	 
			<table class="table table-striped table-bordered table-condensed">

				<tr>
				<th> Date </th>
				<th> Distance </th>
			 	<th> Ridescore </th>
			 	<th> Comments </th>
				</tr>
				<% @user.commutes_that_count.order('commute_date asc').each do |commute| %>
					<tr>
					<td> <%= commute.commute_date %> </td>
					<td> <%= commute.distance %> </td>
					<td> <%= commute.ridescore %> </td>
					<% if commute.comments != nil && commute.comments != "" %>
						<td> <i><b>"<%= commute.comments %>"</b></i> </td>
					<% else %>
						<td></td>
					<% end %>
					<td> <%= link_to "View Commute Detail", commute_url(commute.id) %> </td>		
					</tr>
			  	<% end %>
			</table>

	<% else %>

		<p>
		  <b><%= @user.fname %> has not yet logged commutes during Commuter Challenge (Jun 9 - Jun 15)</b>
		</p>
	<% end %>
	<!-- <% if logged_in? && get_user.team_id != nil %>
		<% if is_the_team_leader? || get_user == @user %>
		<%= button_to "+ Add Commute", new_commute_url(:user_id => @user.id), :method => 'get' %> 
		<% end %>	
	<% elsif logged_in? && get_user == @user %>
		<%= link_to "Choose Your Team to Add a Commute!", edit_user_url(@user.id) %>
	<% else  %>
	<% end %> -->
<% end %>	
<br>
<p>
  <b>All <%= @user.fname %>'s Logged Commutes:</b>
</p>
	 
	<table class="table table-striped table-bordered table-condensed">

		<tr>
		<th> Date </th>
		<th> Distance </th>
	 	<th> Ridescore </th>
	 	<th> Comments </th>
		</tr>
		<% @user.commutes.order('commute_date asc').each do |commute| %>
			<tr>
			<td> <%= commute.commute_date %> </td>
			<td> <%= commute.distance %> </td>
			<td> <%= commute.ridescore %> </td>
			<% if commute.comments != nil && commute.comments != "" %>
				<td> <i><b>"<%= commute.comments %>"</b></i> </td>
			<% else %>
				<td></td>
			<% end %>
			<td> <%= link_to "View Commute Detail", commute_url(commute.id) %> </td>		
			</tr>
	  	<% end %>
	</table>


	<!-- <% if logged_in? && get_user.team_id != nil %>
		<% if is_the_team_leader? || get_user == @user %>
		<%= button_to "+ Add Commute", new_commute_url(:user_id => @user.id), :method => 'get' %> 
		<% end %>	
	<% elsif logged_in? && get_user == @user %>
		<%= link_to "Choose Your Team to Add a Commute!", edit_user_url(@user.id) %>
	<% else  %>
	<% end %>	 -->

app/views/users/surveyinfo.html.erb
<h1>Edit <%= @user.full_name %></h1>

<p id="notice"><%= notice %></p>

	<% if @user.provider !=nil  %>
		<%= render 'surveyform' %>
	<% else  %>
	<%= render 'form' %>
	<% end  %>

<%= link_to 'Cancel', @user %>