config/routes.rb
Btww1::Application.routes.draw do

  get '/contest_ended' => 'greetings#contest_ended', :as => :contestended

  get '/index' => 'greetings#index'
  get '/forgot-password' => 'greetings#forgot-password'
  post '/forgot-password' => 'users#reset_password'

  get '/activate' => 'greetings#activate', :as => :activate

  root :to => 'teams#index'
  
  get '/users/:id/chooseteam' => 'users#edit', :as => :chooseteam
  get '/users/:id/completeprofile' => 'users#completeprofile', :as => :completeprofile
  get '/users/:id/surveyinfo' => 'users#surveyinfo', :as => :surveyinfo
  get '/users/activate' => 'users#activate', :as => :activate_account

  match '/auth/:facebook/callback', to: 'sessions#fb_auth'

  resources :sessions
  
  get '/logout' => 'sessions#destroy', :as => :logout
  
  get '/reports' => 'reports#index', :as => :reports
  get '/reports/commute-comments' => 'reports#commute_comments'
  get '/reports/commute-comments/wordcloud' => 'reports#wordcloud'
  
  get '/reports/teams' => 'reports#teams', :as => :teamsreport
  get '/reports/users' => 'reports#users', :as => :usersreport
  
  get '/reports/team_report' => 'reports#team_report', :as => :teamcsvfile
  get '/reports/user_report' => 'reports#user_report', :as => :usercsvfile

  resources :awards

  resources :commutes

  get '/teams/count' => 'teams#team_count', :as => :teamcount

  resources :teams

  resources :users do
    resources :commutes
  end

end

app/models/award.rb
class Award < ActiveRecord::Base
  
  validates :goal, :company_type, :company_size_range, :presence => :true
  
  has_many :won_awards

  
end

app/controllers/awards_controller.rb
class AwardsController < ApplicationController
  # GET /awards
  # GET /awards.json

  before_filter :require_admin, :except =>  [:index, :show]

  def index
    @awards = Award.find_all_by_goal('Participation Rate')
    @title = "Scoreboards | Bike Commuter Challenge"
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @awards }
    end
  end

  # GET /awards/1
  # GET /awards/1.json
  def show
    @award = Award.find(params[:id])
    @title = "Team Standings for #{@award.company_type} & #{@award.company_size_range} Employees | Bike Commuter Challenge"    

    if @award.isindividual == nil || @award.isindividual == false

      if @award.goal == 'Participation Rate'
           goal = 'team_participation desc'
        elsif @award.goal == 'Total Mileage'
           goal = 'mileage desc'
        elsif @award.goal == 'Number of Newbies'
           goal = 'newbies desc'
        elsif @award.goal == 'Number of Commutes'
           goal = 'total_commutes desc'
        elsif @award.goal == 'Total Commuters'
           goal = 'total_commuters desc'
        else goal = 'company asc'
      end

      @teams = Team.where(:company_type => @award.company_type,
                          :company_size_range => @award.company_size_range,)
                    .order("#{goal}")
            
      @award_list = Award.where(:company_type => @award.company_type,
                                  :company_size_range => @award.company_size_range)
 
    else

     commuters = User.joins(:commutes).select("distinct(users.id)")
        @users = Array.new
        commuters.each do |commuter|
          @users << User.find_by_id(commuter)
        end
      
     @award_list = Award.where(:isindividual => true)
    
    end
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @award }
    end
  end

  # GET /awards/new
  # GET /awards/new.json
  def new
    @award = Award.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @award }
    end
  end

  # GET /awards/1/edit
  def edit
    @award = Award.find(params[:id])
  end

  # POST /awards
  # POST /awards.json
  def create
    @award = Award.new(params[:award])

    respond_to do |format|
      if @award.save
        format.html { redirect_to @award, notice: 'Award was successfully created.' }
        format.json { render json: @award, status: :created, location: @award }
      else
        format.html { render action: "new" }
        format.json { render json: @award.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /awards/1
  # PUT /awards/1.json
  def update
    @award = Award.find(params[:id])

    respond_to do |format|
      if @award.update_attributes(params[:award])
        format.html { redirect_to @award, notice: 'Award was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @award.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /awards/1
  # DELETE /awards/1.json
  def destroy
    @award = Award.find(params[:id])
    @award.destroy

    respond_to do |format|
      format.html { redirect_to awards_url }
      format.json { head :ok }
    end
  end
end

app/helpers/awards_helper.rb
module AwardsHelper
end

app/views/awards/_form.html.erb
<%= form_for(@award) do |f| %>
  <% if @award.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@award.errors.count, "error") %> prohibited this award from being saved:</h2>

      <ul>
      <% @award.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field" id="goal">
    <%= f.label :goal %>
    <%= f.select(:goal, ['Participation Rate', 'Number of Commutes', 'Number of Newbies', 'Total Mileage', 'Highest Mileage in One Day'],
 				{:prompt => 'Select One'}) %>

  <div class="field" id="team_checkbox">
    <%= f.label :isteam, "Check if this is a Team Award" %>
    <%= f.check_box :isteam %>
  </div>
  <div class="field" id="company_type">
    <%= f.label :company_type %>
    <%= f.select(:company_type, ['Business', 'Non-Profit', 'Education', 'Bike-Related', 'Government', 'Transportation-Related'],
 				{:prompt => 'Select One'}) %>
  </div>
  <div class="field" id="company_size">
    <%= f.label :company_size_range, "Company Size" %>
    <%= f.select(:company_size_range, ['1-5', '6-20', '21-50', '51-100', '101-300', '301-1000', '1001+'],
 				{:prompt => 'Select One'}) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/awards/edit.html.erb
<h1>Editing award</h1>

<%= render 'form' %>

<%= link_to 'Cancel', @award %> |
<%= link_to 'Back', awards_path %>

app/views/awards/index.html.erb
<h1>Team Standings!</h1>
<br>
<table class="table table-striped table-bordered table-condensed">

  <tr>
    <th>Company type</th>
    <th>Company size range</th>
    <th></th>
  </tr>

<% @awards.each do |award| %>
  <tr>
    <td><%= award.company_type %></td>
    <td><%= award.company_size_range %></td>
	<% if num_competing_teams(award) > 0 %>
		<td><%= link_to "Team Standings", award_url(award.id) %> <%= "(#{num_competing_teams(award)} Teams)" %></td>
	<% else %>
		<% if !logged_in? %>
		<td><!-- <%= link_to "+ Add Your Team", new_user_url %> --> <%= "(#{num_competing_teams(award)} Teams)" %></td>		
		<% else %>
		<td><%= "(#{num_competing_teams(award)} Teams)" %></td>
		<% end %>
	<% end %>
  </tr>
<% end %>
</table>

<br />

<% if logged_in? && isadmin?  %>
<%= link_to 'New Award', new_award_path %>
<% end %>

app/views/awards/new.html.erb
<h1>New award</h1>

<%= render 'form' %>

<%= link_to 'Back', awards_path %>

app/views/awards/show.html.erb
<p id="notice"><%= notice %></p>

<% if @award.isteam = true %>
	<h1>Commuter Challenge Team Standings </h1>
	<h3>Category: <%= @award.company_type.upcase %> Organizations with <%= @award.company_size_range %> EMPLOYEES </h3>
	<%= link_to '(Standings for Other Categories)', awards_path, :method => 'get' %>
	<br>
	<br>


	<div id='fb-share-button'> </div>

	<div id='fb-root'></div>
	    <script src='http://connect.facebook.net/en_US/all.js'></script>
	    <p><a onclick='postToFeed(); return false;'> <%= image_tag("facebook_share_button.jpg", :width => '60') %></a>


	    <script> 
	       FB.init({appId: 204090116364336, status: true, cookie: true});

	      function postToFeed() {

	        // calling the API ...
	        var obj = {
	          method: 'feed',
	          link: '<%= url_for award_url %>',
	          picture: 'http://activetrans.org/htmlemail/ata.png',
	          name: 'Check out my company scoreboard for Bike Commuter Challenge!',
	          caption: 'Active Transportation Alliance Commuter Challenge',
	          description: 'Sign up your company to compete!',
			  message: 'Check out my company on the Bike Commuter Challenge Scoreboard'
	        };

	        function callback(response) {
	          document.getElementById('msg').innerHTML = "Post ID: " + response['post_id'];
	        }

	        FB.ui(obj, callback);
	      }

	    </script>

		<a href="https://twitter.com/share" class="twitter-share-button" data-text="Check out Bike Commuter Challenge TEAM STANDINGS!" data-count="none">Tweet</a>
		<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script></p>
		    <p id='msg'></p>

<br>

<p> 
<b>	Sort Teams By: </b><% @award_list.each do |award| %>
		<% if award.id != @award.id  %>
			<%= link_to "#{award.goal}", award_url(award.id) %> | 
			<% else  %>
			<%= award.goal %> | 
		<% end  %>
	<% end  %>
</p>
<p><i>Note: Bike Commuter Challenge Winners are determined using Participation Rate (Total Commuters / # of Employees) </i></p>



	<br>

		<table class="table table-striped table-bordered table-condensed">
			<tr>
				<th> Team Name </th>
				<th> Current Place </th>			
				<th> Total Participation Rate </th>			
				<th> Total Employees </th>			
				<th> Total Commuters </th>			
				<th> Qualifying Commutes (Logged 6/9-6/15)  </th>		
				<th> Total Mileage </th>			
				<th> Newbies </th>			
				<th> Team Members yet to Log a Qualifying Commute  </th>			
	
			</tr>
		<% if @teams != nil %>
			<% place = 1 %>
			<% @teams.each do |team| %>

				<tr>
				<% if place == 1 && @award.goal == 'Participation Rate' %>
					<td> <b><%= link_to "#{team.company}", team_url(team.id) %> (Current Leader)</b> </td>
					<td> <b><%= place %></b> </td>
					<td> <b><%= team.team_participation %>%</b> </td>
				<% else %>
					<td> <%= link_to "#{team.company}", team_url(team.id) %> </td>
					<td> <%= place %> </td>
					<td> <%= team.team_participation %>% </td>					
				<% end %>										
					<td> <%= team.size %> </td>
					<td> <%= team.commuters %> </td>
					<td> <%= team.commutes_that_count.count %> </td>
					<td> <%= team.mileage %> </td>
					<td> <%= team.newbies %> </td>
					<td> <%= team.zero_commutes %> </td>
				</tr>
					<% place = place + 1 %>
			<% end %>
		<% end %>
		</table>

<%= button_to "+ Add a Team", new_team_url, :method => 'get' %>

<% else %>
	<table class="table table-striped table-bordered table-condensed">
		<tr>
			<th> Commuter Name </th>
			<th> Commutes </th>
			<th> Total Mileage </th>
		</tr>
		<% @users.each do |user| %>
			<tr>
				<td> <%= user.fname %> </td>
				<td> <%= user.commutes.count %> </td>
				<td> <%= user.mileage %> </td>
			</tr>
		<% end %>
	</table>


<% end %>
<br>


<br>
<br>