config/routes.rb
Btww1::Application.routes.draw do

  get '/contest_ended' => 'greetings#contest_ended', :as => :contestended

  get '/index' => 'greetings#index'
  get '/forgot-password' => 'greetings#forgot-password'
  post '/forgot-password' => 'users#reset_password'

  get '/activate' => 'greetings#activate', :as => :activate

  root :to => 'teams#index'
  
  get '/users/:id/chooseteam' => 'users#edit', :as => :chooseteam
  get '/users/:id/completeprofile' => 'users#completeprofile', :as => :completeprofile
  get '/users/:id/surveyinfo' => 'users#surveyinfo', :as => :surveyinfo
  get '/users/activate' => 'users#activate', :as => :activate_account

  match '/auth/:facebook/callback', to: 'sessions#fb_auth'

  resources :sessions
  
  get '/logout' => 'sessions#destroy', :as => :logout
  
  get '/reports' => 'reports#index', :as => :reports
  get '/reports/commute-comments' => 'reports#commute_comments'
  get '/reports/commute-comments/wordcloud' => 'reports#wordcloud'
  
  get '/reports/teams' => 'reports#teams', :as => :teamsreport
  get '/reports/users' => 'reports#users', :as => :usersreport
  
  get '/reports/team_report' => 'reports#team_report', :as => :teamcsvfile
  get '/reports/user_report' => 'reports#user_report', :as => :usercsvfile

  resources :awards

  resources :commutes

  get '/teams/count' => 'teams#team_count', :as => :teamcount

  resources :teams

  resources :users do
    resources :commutes
  end

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  
  before_filter :require_admin
  
  def index
    @team_count = Team.count

    @public_count = Team.where(:company_type => 'Public Agency').count
    @busnp_count = Team.where(:company_type => 'Business/Non-Profit').count
    @bike_count = Team.where(:company_type => 'Bicycle-related Business').count
    @k12_count = Team.where(:company_type => 'K-12 School').count
    @college_count = Team.where(:company_type => 'College/University').count

    @vysm_count = Team.where(:company_size_range => '1-4').count
    @sm_count = Team.where(:company_size_range => '5-24').count
    @med_count = Team.where(:company_size_range => '25-99').count
    @lrg_count = Team.where(:company_size_range => '100-499').count
    @huge_count = Team.where(:company_size_range => '500+').count

    @user_count = User.count
    @newbies_count = User.where(:isnewbie => true).count

    @transpo_count = User.where(:bikerclass => 'Commuter/Transportation').count
    @rec_count = User.where(:bikerclass => 'Recreational').count
    @roadies_count = User.where(:bikerclass => 'Roadie').count
    @mtb_count = User.where(:bikerclass => 'MTB/Cross').count
    @bmx_count = User.where(:bikerclass => 'BMX').count

    @commute_count = Commute.count
    @bcc_commute_count = Commute.where(:commute_date => '2012-06-09'..'2012-06-15').count

    @bcc_sat_commute_count = Commute.where(:commute_date => '2012-06-09').count
    @bcc_sun_commute_count = Commute.where(:commute_date => '2012-06-10').count
    @bcc_mon_commute_count = Commute.where(:commute_date => '2012-06-11').count
    @bcc_tue_commute_count = Commute.where(:commute_date => '2012-06-12').count
    @bcc_wed_commute_count = Commute.where(:commute_date => '2012-06-13').count
    @bcc_thu_commute_count = Commute.where(:commute_date => '2012-06-14').count
    @bcc_fri_commute_count = Commute.where(:commute_date => '2012-06-15').count

    @bcc_fantastic_commute_count = Commute.where(:ridescore => 'Fan-freakin-tastic!').count
    @bcc_good_commute_count = Commute.where(:ridescore => 'Hella Good').count
    @bcc_meh_commute_count = Commute.where(:ridescore => 'Meh').count
    @bcc_hurtin_commute_count = Commute.where(:ridescore => "Hurtin'").count
    @bcc_abysmal_commute_count = Commute.where(:ridescore => 'Abysmal').count

    
  end
  
  def teams
    @teams = Team.all
    
  end
    
  def users
    @users = User.all
    
  end
  
  def commute_comments
    if params[:date]
      @commutes = Commute.where("commute_date = ?", params[:date])
    else
      @commutes = Commute.all
    end
  end
  
  def wordcloud

  end
  
  
  def team_report
    # for csv_builder
    # TODO - @teamname = param value pointing to  team name here
    # @filename = 'report.csv'
    @output_encoding = 'UTF-8'
    @csv_options = { :force_quotes => true, :col_sep => ';' }
    # for csv_builder end
    
    respond_to do |format|
        format.html # team_report.html.erb
        # format.xml  { render :xml => @payments }
        format.csv do
            # timestamping your files is a nice idea if the user runs this action more than once...
            timestamp = Time.now.strftime('%Y-%m-%d_%H:%M:%S')
            # passing a meaningful filename is a nice touch
            @filename = "team_report_#{timestamp}.csv"
        end
    end
  end
  
  def user_report
    # for csv_builder
    @output_encoding = 'UTF-8'
    @csv_options = { :force_quotes => true, :col_sep => ';' }
    # for csv_builder end
    
    respond_to do |format|
        format.html # user_report.html.erb
        # format.xml  { render :xml => @payments }
        format.csv do
            # timestamping your files is a nice idea if the user runs this action more than once...
            timestamp = Time.now.strftime('%Y-%m-%d_%H:%M:%S')
            # passing a meaningful filename is a nice touch
            @filename = "user_report_#{timestamp}.csv"
        end
    end
  end
  
end

app/views/reports/commute_comments.html.erb
	<table>
	  <tr>
	    <!-- <th>Ridescore</th> -->
	    <th>Comment</th>
	  </tr>

	<% @commutes.each do |commute| %>
	  <tr>
	    <!-- <td><%= commute.ridescore %></td> -->
	    <td><%= commute.comments %></td>
	  </tr>
	<% end %>


</table>

app/views/reports/index.html.erb
<h1> Bike Commuter Challenge 2012 Reports and Stats</h1>
<br>
<h3> Teams</h3>
<b>Number of Teams: <%= @team_count %></b>
<br>
<br>
<b>Teams by Company Type</b>
<br>
Public Agency: <%= @public_count %>
<br>
Business/Non-Profit: <%= @busnp_count %>
<br>
Bicycle-related Business: <%= @bike_count %>
<br>
K-12 School: <%= @k12_count %>
<br>
College/University: <%= @college_count %>
<br>
<br>
<b>Teams by Company Size</b>
<br>
1-4 Employees: <%= @vysm_count %>
<br>
5-24 Employees: <%= @sm_count %>
<br>
25-99 Employees: <%= @med_count %>
<br>
100-499 Employees: <%= @lrg_count %>
<br>
500+ Employees: <%= @huge_count %>
<br>
<br>
<h3> Users </h3>
<b>Number of Users: <%= @user_count %></b>
<br>
<b>Bike to Work Newbies: <%= @newbies_count %></b>
<br>
<br>
<b>Users by self-described "Primary Biker Type"</b>
<br>
Recreational: <%= @rec_count %>
<br>
Transportation/Commuter: <%= @transpo_count %>
<br>
Roadies: <%= @roadies_count %>
<br>
Mountain Bike / Cross Riders: <%= @mtb_count %>
<br>
BMX Riders: <%= @bmx_count %>
<br>
<br>
<h3> Commutes</h3>
<b>Number of Commutes: <%= @commute_count %></b>
<br>
<b>"Qualifying" Commuter Challenge Commutes: <%= @bcc_commute_count %></b>
<br>
Jun 9 (Saturday) Commutes: <%= @bcc_sat_commute_count %>
<br>
Jun 10 (Sunday) Commutes: <%= @bcc_sun_commute_count %>
<br>
Jun 11 (Monday) Commutes: <%= @bcc_mon_commute_count %>
<br>
Jun 12 (Tuesday) Commutes: <%= @bcc_tue_commute_count %>
<br>
Jun 13 (Wednesday) Commutes: <%= @bcc_wed_commute_count %>
<br>
Jun 14 (Thursday) Commutes: <%= @bcc_thu_commute_count %>
<br>
Jun 15 (Friday) Commutes: <%= @bcc_fri_commute_count %>
<br>
<br>
<b>Commutes by how the rider felt:</b>
<br>
"Fan-freakin-tastic": <%= @bcc_fantastic_commute_count %>
<br>
"Hella Good": <%= @bcc_good_commute_count %>
<br>
"Meh": <%= @bcc_meh_commute_count %>
<br>
"Hurtin'": <%= @bcc_hurtin_commute_count %>
<br>
"Abysmal": <%= @bcc_abysmal_commute_count %>
<br>
<br>
<b>Commuter Comments:</b>
<br>
<%= link_to "WORD CLOUD IMAGES of each day", "/reports/commute-comments/wordcloud" %>
<br>
<%= link_to "June 9 - Saturday", "/reports/commute-comments/?date=2012-06-09" %>
<br>
<%= link_to "June 10 - Sunday", "/reports/commute-comments/?date=2012-06-10" %>
<br>
<%= link_to "June 11 - Monday", "/reports/commute-comments/?date=2012-06-11" %>
<br>
<%= link_to "June 12 - Tuesday", "/reports/commute-comments/?date=2012-06-12" %>
<br>
<%= link_to "June 13 - Wednesday", "/reports/commute-comments/?date=2012-06-13" %>
<br>
<%= link_to "June 14 - Thursday", "/reports/commute-comments/?date=2012-06-14" %>
<br>
<%= link_to "June 15 - Friday", "/reports/commute-comments/?date=2012-06-15" %>
<br>
<%= link_to "All Comments", "/reports/commute-comments" %>

<br>
<br>
<table>
<tr>
<td><%= button_to "Teams Report", teamsreport_url, :method => 'get' %></td>
<td><%= button_to "Users Report", usersreport_url, :method => 'get' %></td>
</tr>
</table>

app/views/reports/teams.html.erb
<h1> Teams Report </h1>

<table id="report" class="table table-striped table-bordered table-condensed">
  <tr>
    <th>Company</th>
    <th>Company type</th>
    <th>Size</th>
    <th>Size Range</th>
    <th>Leader First Name</th>
    <th>Leader Last Name</th>
    <th>Leader Email</th>
    <th>Shirt</th>
    <th>Address Line 1</th>
    <th>Address Line 2</th>
    <th>City</th>
    <th>State</th>
    <th>ZIP</th>
    <th>Phone</th>
    <th>Twitter</th>
    <th>Website</th>
    <th>Team Created</th>
    <th>Team Updated</th>
    <th>Company Size</th>
    <th>Members who Logged at least 1 Commute during BTTW</th>
    <th>Team Participation Rate</th>
    <th>Team Commutes</th>
    <th>Team Mileage</th>
    <th>Team Members with 0 Commutes</th>
    <th>Team Page</th>


  </tr>

<% @teams.each do |team| %>
  <tr>
    <td><%= team.company %></td>
    <td><%= team.company_type %></td>
    <td><%= team.size %></td>
    <td><%= team.company_size_range %></td>
    <td><%= "#{User.find(team.leader).fname}" %></td>
    <td><%= "#{User.find(team.leader).lname}" %></td>
    <td><%= "#{User.find(team.leader).email}" %></td>
    <td><%= team.shirt_size %></td>
    <td><%= team.address_line_1 %></td>
    <td><%= team.address_line_2 %></td>
    <td><%= team.city %></td>
    <td><%= team.state %></td>
    <td><%= team.zip %></td>
    <td><%= team.phone %></td>
    <td><%= team.twitter_handle %></td>
    <td><%= team.website %></td>
    <td><%= team.created_at %></td>
    <td><%= team.updated_at %></td>
    <td><%= team.size %></td>
    <td><%= team.commuters %></td>
    <td><%= team.team_participation %></td>
    <td><%= team.total_commutes %></td>
    <td><%= team.mileage %></td>
    <td><%= team.zero_commutes %></td>
    <td><%= link_to "#{team.company}", team_url(team) %></td>

  </tr>
<% end %>
</table>

<!-- <input value="Export as CSV" type="button" onclick="$('#report').table2CSV(separator : '/t')"> -->

<%= link_to 'Download Report as CSV', teamcsvfile_path(:format => :csv) %>

app/views/reports/users.html.erb
<h1>Users</h1>
<br>
	<table class="table table-striped table-bordered table-condensed">

		<tr>
		<th> First Name </th>
		<th> Last Name </th>
		<th> Email Address</th>
		<th> 3rd party Login?</th>
		<th> ActiveTrans Email List Opt-in </th>
		<th> BTWW event Email List Opt-in </th>
		<th> Team </th>		
		<th> Team Leader? </th>		
		<th> Created On </th>		
		<th> Updated On </th>		
		<th> Newbie? </th>		
	 	<th> Self-Described Biker Type </th>
	 	<th> User Profile Link </th>
	 	<th> BTWW Mileage </th>
		</tr>

		<% @users.each do |user| %>
		<tr>
		<td> <%= user.fname %> </td>
		<td> <%= user.lname %> </td>
		<td> <%= user.email %> </td>
		<td> <%= user.provider %> </td>
		<td> <%= user.general_email_list %> </td>
		<td> <%= user.btww_email_list %> </td>
			<% if user.team != nil %>
				<td> <%= "#{user.team.company}" %> </td>
				<% if user.id == user.team.leader %>
				<td> Y </td>		
				<% else %>
				<td> N </td>	
				<% end %>
			<% else  %>
				<td>  </td>
				<td> N </td>				
			<% end  %>	
		<td> <%= user.created_at %> </td>
		<td> <%= user.updated_at %> </td>
		<% if user.isnewbie == true %>
		<td> Y </td>		
		<% else %>
		<td> N </td>	
		<% end %>	
		<td> <%= user.bikerclass %> </td>
		<td> <%= link_to "#{user.full_name}", user_url(user) %> | <%= link_to "User ID: #{user.id}", user_url(user) %> </td>
		<td> <%= user.mileage %> </td>
		</tr>
<% end %>
	</table>
	
	
<%= link_to 'Download Report as CSV', usercsvfile_path(:format => :csv) %>

app/views/reports/wordcloud.html.erb
<h1>Bike Commuter Comments - In Word Clouds</h1>
<br>
<br>
<h2>June 9 - Saturday</h2>

<a href="http://www.wordle.net/show/wrdl/5482469/Chicago_Bike_Commuter_Challenge_-_Day_1" 
          title="Wordle: Chicago Bike Commuter Challenge - Day 1"><img
          src="http://www.wordle.net/thumb/wrdl/5482469/Chicago_Bike_Commuter_Challenge_-_Day_1"
          alt="Wordle: Chicago Bike Commuter Challenge - Day 1"
          style="padding:4px;border:1px solid #ddd"></a>


<h2>June 10 - Sunday</h2>
<a href="http://www.wordle.net/show/wrdl/5482485/Chicago_Bike_Commuter_Challenge_-_Day_2" 
          title="Wordle: Chicago Bike Commuter Challenge - Day 2"><img
          src="http://www.wordle.net/thumb/wrdl/5482485/Chicago_Bike_Commuter_Challenge_-_Day_2"
          alt="Wordle: Chicago Bike Commuter Challenge - Day 2"
          style="padding:4px;border:1px solid #ddd"></a>


<h2>June 11 - Monday</h2>
<a href="http://www.wordle.net/show/wrdl/5482495/Chicago_Bike_Commuter_Challenge_-_Day_3" 
          title="Wordle: Chicago Bike Commuter Challenge - Day 3"><img
          src="http://www.wordle.net/thumb/wrdl/5482495/Chicago_Bike_Commuter_Challenge_-_Day_3"
          alt="Wordle: Chicago Bike Commuter Challenge - Day 3"
          style="padding:4px;border:1px solid #ddd"></a>


<h2>June 12 - Tuesday</h2>
<a href="http://www.wordle.net/show/wrdl/5482500/Bike_Commuter_Challenge_-_Day_4" 
          title="Wordle: Bike Commuter Challenge - Day 4"><img
          src="http://www.wordle.net/thumb/wrdl/5482500/Bike_Commuter_Challenge_-_Day_4"
          alt="Wordle: Bike Commuter Challenge - Day 4"
          style="padding:4px;border:1px solid #ddd"></a>


<h2>June 13 - Wednesday</h2>
<a href="http://www.wordle.net/show/wrdl/5482506/Bike_Commuter_Challenge_-_Day_5" 
          title="Wordle: Bike Commuter Challenge - Day 5"><img
          src="http://www.wordle.net/thumb/wrdl/5482506/Bike_Commuter_Challenge_-_Day_5"
          alt="Wordle: Bike Commuter Challenge - Day 5"
          style="padding:4px;border:1px solid #ddd"></a>


<h2>June 14 - Thursday</h2>
<a href="http://www.wordle.net/show/wrdl/5482512/Chicago_Bike_Commuter_Challenge_-_Day_6" 
          title="Wordle: Chicago Bike Commuter Challenge - Day 6"><img
          src="http://www.wordle.net/thumb/wrdl/5482512/Chicago_Bike_Commuter_Challenge_-_Day_6"
          alt="Wordle: Chicago Bike Commuter Challenge - Day 6"
          style="padding:4px;border:1px solid #ddd"></a>


<h2>June 15 - Friday</h2>
<a href="http://www.wordle.net/show/wrdl/5482520/Chicago_Bike_Commuter_Challenge_-_Day_7" 
          title="Wordle: Chicago Bike Commuter Challenge - Day 7"><img
          src="http://www.wordle.net/thumb/wrdl/5482520/Chicago_Bike_Commuter_Challenge_-_Day_7"
          alt="Wordle: Chicago Bike Commuter Challenge - Day 7"
          style="padding:4px;border:1px solid #ddd"></a>