config/routes.rb
Btww1::Application.routes.draw do

  get '/contest_ended' => 'greetings#contest_ended', :as => :contestended

  get '/index' => 'greetings#index'
  get '/forgot-password' => 'greetings#forgot-password'
  post '/forgot-password' => 'users#reset_password'

  get '/activate' => 'greetings#activate', :as => :activate

  root :to => 'teams#index'
  
  get '/users/:id/chooseteam' => 'users#edit', :as => :chooseteam
  get '/users/:id/completeprofile' => 'users#completeprofile', :as => :completeprofile
  get '/users/:id/surveyinfo' => 'users#surveyinfo', :as => :surveyinfo
  get '/users/activate' => 'users#activate', :as => :activate_account

  match '/auth/:facebook/callback', to: 'sessions#fb_auth'

  resources :sessions
  
  get '/logout' => 'sessions#destroy', :as => :logout
  
  get '/reports' => 'reports#index', :as => :reports
  get '/reports/commute-comments' => 'reports#commute_comments'
  get '/reports/commute-comments/wordcloud' => 'reports#wordcloud'
  
  get '/reports/teams' => 'reports#teams', :as => :teamsreport
  get '/reports/users' => 'reports#users', :as => :usersreport
  
  get '/reports/team_report' => 'reports#team_report', :as => :teamcsvfile
  get '/reports/user_report' => 'reports#user_report', :as => :usercsvfile

  resources :awards

  resources :commutes

  get '/teams/count' => 'teams#team_count', :as => :teamcount

  resources :teams

  resources :users do
    resources :commutes
  end

end

app/views/layouts/_facebook_dialogs.html.erb
<div id="fb-root"></div>
<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : 204090116364336, // App ID
      channelUrl : 'www.bike2workweek.com/channel.html', // Channel File
      status     : true, // check login status
      cookie     : true, // enable cookies to allow the server to access the session
      xfbml      : true  // parse XFBML
    });

    // Additional initialization code here
  };

  // Load the SDK Asynchronously
  (function(d){
     var js, id = 'facebook-jssdk', ref = d.getElementsByTagName('script')[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement('script'); js.id = id; js.async = true;
     js.src = "//connect.facebook.net/en_US/all.js";
     ref.parentNode.insertBefore(js, ref);
   }(document));
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<html xmlns="http://www.w3.org/1999/xhtml"
  xmlns:fb="https://www.facebook.com/2008/fbml">
  <head>
    <meta charset="utf-8">
    <title><%= @title %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <!-- Le styles -->
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>
    <%= stylesheet_link_tag "application", :media => "all" %>


    <!-- Le fav and touch icons -->
    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">

    <!-- Google Analytics -->
	<script type="text/javascript">

	  var _gaq = _gaq || [];
	  _gaq.push(['_setAccount', 'UA-29684552-1']);
	  _gaq.push(['_trackPageview']);

	  (function() {
	    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
	    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
	    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	  })();

	</script>

    <!-- UserVoice -->
	<script type="text/javascript">
	  var uvOptions = {};
	  (function() {
	    var uv = document.createElement('script'); uv.type = 'text/javascript'; uv.async = true;
	    uv.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'widget.uservoice.com/3HskhdXXC1BGzpwJWg5Cw.js';
	    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(uv, s);
	  })();
	</script>
  </head>
  <body>
      <div class="ataheader">

      </div>

      <div class="clearboth"></div>   
	<%= render 'layouts/facebook_dialogs' %> 
    <div class="logo">
      <%= link_to image_tag("bcc_logo_dropshadow__3.png", :border=>0), 'http://bikecommuterchallenge.org/' %>  
    </div>
    <div class="navbar">
      <div class="navbar-inner">
          <div class="container">
          <!-- <a class="brand" href="/">Bike Commuter Challenge</a> -->
          <div class="navcontainer" data-toggle="collapse" data-target=".nav-collapse">
            <ul class="nav pull-right">
				<li id="current-choice"><%= link_to "Registration & Standings", root_url %></li>
				<li id="main-nav-links"><a href="http://bikecommuterchallenge.org/about">About</a></li>
				<li id="main-nav-links"><a href="http://bikecommuterchallenge.org/teamleader">Team Leader Info</a></li>
				<li id="main-nav-links"><a href="http://bikecommuterchallenge.org/pitstops">Pit Stops</a></li>
				<li id="main-nav-links"><a href="http://bikecommuterchallenge.org/howto">How To Bike To Work</a></li>
				<li id="main-nav-links"><a href="http://bikecommuterchallenge.org/sponsors">Sponsors</a></li>														
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
      <% if session[:user_id] != nil && get_user != nil %>
      <div class="subnav subnav-fixed">
        <div class="subnavcontainer-fluid">
        <ul class="nav nav-pills pull-right">
            <% if get_user.provider != nil %>
				<li id="subtn"><%= image_tag("http://graph.facebook.com/#{get_user.uid}/picture?type=square") %></li>
			<% end %>
				<li id="subtn"><%= link_to "#{get_user.fname}", user_url(get_user.id)%> </li>
			<% if get_user.team != nil %>
				<li id="subtn"><%= link_to "My Team", team_url(get_user.team.id) %></li>
					<% if get_user.team.company_size_range != nil && get_user.team.company_size_range != "" %>
						<li id="subtn"><%= link_to "Our Standings", award_url(users_scoreboard(get_user).id) %></li>
					<% end %>
			<% end %>
				<li id="subtn"><%= link_to "My Commutes", user_url(get_user.id) %></li>
				<!-- <li id="subtn"><%= link_to "Log New Commute", new_commute_url, :user_id => get_user.id %></li> -->
		<% if get_user.isadmin? %>
                <li id="subtn"><%= link_to "Reports", reports_url %></li>
		<% end %>
				<li id="subtn"><%= link_to "Sign Out", logout_url %></li>
		</ul> 
	  </div>
	  </div>

		<% else %>
			
		<div class="nav-collapse"> <!-- disapear me at 940 less -->
        <div class="subnav subnav-fixed">           
        <div class="subnavcontainer-fluid">
        <ul class="nav nav-pills pull-right">
            <!-- <li id="subtn"><%= link_to "+ Log New Commute", new_commute_url %></li> -->
            <li id="subtn"><%= link_to "Team Standings", awards_url %></li>
            <li id="subtn"><%= link_to "Sign In", new_session_url %></li>
            <!-- <li id="subtn"><%= link_to "Sign Up", new_user_url  %></li> -->
            <li><%= link_to image_tag("login_fb.jpeg", :border=>0), '/auth/facebook' %> </li>
        </ul>
        </div>  			
        </div>
        </div>
        <% end %>
      </div>
    </div>

    <!-- navbar ends -->

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div id="fonso_spacer">
              <!-- THIS HOLDS SPACE OVER BIKEDUDE -->
          </div><!--/.well -->
        </div><!--/span-->
        <div id="fonso" class="span9">
          <%= yield %>
        </div>
      </div><!--/row-->


      <footer>
        <p></p>
		<%= yield :scripts %>
      </footer>

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>